title: 学无止境 #博客标题
description: Just Fun. #博客描述
keywords: blog,css,html,php #博客关键字

#title hide and show
hide: (つェ⊂)我藏好啦
show: ´∇｀ 呀被发现啦~ 

baseurl: ""
url: "3guoyanyi.github.io" # change this to the base hostname & protocol for your site
bulidtime: "1514736000" #博客建立时的时间戳 可进入https://tool.lu/timestamp/将博客建立时的日期转换成时间戳
           #The timestamp at the time of blog establishment can be entered at https://tool.lu/timestamp/to convert the date at the time of blog establishment into a timestamp.

paginate: 8 #同时显示的最大文章数，超过自动分页
paginate_path: "page:num"

background: https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1563551063266&di=4e6fe8184b97f133a53176726b010e0f&imgtype=0&src=http%3A%2F%2Fb-ssl.duitang.com%2Fuploads%2Fitem%2F201806%2F30%2F20180630190713_cclyb.jpg
theme_color: 546E7A

google_analytics:
# hydrogen-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
hydrogen-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

#install emoji
plugins:
  - jemoji

# social
author: "学无止境"
image:
twitter:
username: "王佳亮"
#  site:
facebook:
  #publisher: null
  #profile_id: null
  app_id: null
  #authors: null
#  admins:
